[package]
name = "flow2flow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["inmem-registry"]
inmem-registry = ["once_cell"]

[dependencies]
flow2flow-contract = { workspace = true }
flow2flow-runtime = { workspace = true }
flow2flow-router-adapter = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
once_cell = { workspace = true, optional = true }

[dev-dependencies]
insta = { workspace = true }
